# https://snarky.ca/what-the-heck-is-pyproject-toml/
[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "Cython", "luckydonald-utils>=0.82", "cffi>=1.0.0"]
build-backend = "setuptools.build_meta"
